In [38]:
# Import Required Libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import StackingClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score

In [3]:
# Import Dataset
df=pd.read_csv('heart.csv')
df.head(2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1

In [4]:
# Show the basic information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [5]:
# Extract input and output feature
X=df.drop(columns='target', axis=1)
y=df['target']

In [26]:
# Split the data into train and test set
X_train, X_test, y_train, y_test=train_test_split(
    X,y,
    test_size=0.2,
    random_state=42
)

In [30]:
# Perform StandardScalar transformation on few columns
sc=StandardScaler()
# Transform the selected column
var_transform = ['thalach', 'age', 'trestbps', 'oldpeak', 'chol']

X_train[var_transform]=sc.fit_transform(X_train[var_transform])
X_test[var_transform]=sc.transform(X_test[var_transform])
X_train.head(2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,-1.356798,1,1,-0.616856,0.914034,0,1,0.532781,0,-0.920864,2,0,2
202,0.385086,1,0,1.169491,0.439527,0,0,-1.753582,1,-0.193787,2,0,3

In [31]:
# Now perform model evaluation
# Create object of Kneighboursclassifier and GuassianNB
model_KN=KNeighborsClassifier()
model_GN=GaussianNB()

In [49]:
# Training and Evaluating the KNeighborsClassifier
model_KN.fit(X_train,y_train)
y_pred=model_KN.predict(X_test)
# Show the accuracy of the model
print('The accuracy of KneighboursClassifier:', round(accuracy_score(y_pred, y_test)*100,2))

The accuracy of KneighboursClassifier: 86.89

In [48]:
# Evaluate and make prediction of GaussiuanNB
model_GN.fit(X_train, y_train)
y_pred_NB=model_GN.predict(X_test)
# Show the accuracy of the model
print('The accuracy of GuassianNB:', round(accuracy_score(y_pred_NB, y_test)*100,2))

The accuracy of GuassianNB: 86.89

In [45]:
# Implementing the StackingClassifier
base_learners=[
    ('KN', KNeighborsClassifier()),
    ('GN', GaussianNB())
]
meta_model = LogisticRegression()

stacking_model=StackingClassifier(
    estimators=base_learners, 
    final_estimator=meta_model,
    cv=5
)

In [47]:
# Training Stacking Classifier  
stacking_model.fit(X_train, y_train)
y_pred_stacking=stacking_model.predict(X_test)

# Show the accuracy
print('The accuracy of stacking model:', round(accuracy_score(y_pred_stacking, y_test)*100,2))

The accuracy of stacking model: 88.52

In [ ]:
# After stacking improve the accuracy